# 1. Identifikasi Kebutuhan Data (Titanic Dataset)

Proyek ini ditujukan untuk mengembangkan model prediktif yang menjawab pertanyaan: “Orang seperti apa yang lebih mungkin selamat dalam insiden tenggelamnya kapal Titanic?” menggunakan data penumpang (misalnya nama, usia, jenis kelamin, kelas sosial ekonomi, dll). Fitur yang relevan antara lain:

| Fitur              | Alasan Penting                                                             | Ketersediaan Data                   |
| ------------------ | -------------------------------------------------------------------------- | ----------------------------------- |
| `Survived`         | Target: 1 = selamat, 0 = meninggal                                         | Tersedia                            |
| `Pclass`           | Kelas tiket → kelas sosial bisa memengaruhi peluang selamat                | Tersedia                            |
| `Sex`              | Jenis kelamin → penumpang wanita lebih mungkin selamat                     | Tersedia                            |
| `Age`              | Usia → anak-anak lebih mungkin diselamatkan                                | Tersedia                            |
| `SibSp`            | Jumlah saudara/ pasangan di kapal → memengaruhi kelangsungan hidup         | Tersedia                            |
| `Parch`            | Jumlah orang tua/anak di kapal → bisa memengaruhi keselamatan              | Tersedia                            |
| `Fare`             | Harga tiket → indikasi status sosial                                       | Tersedia                            |
| `Embarked`         | Pelabuhan naik → beberapa analisis menunjukkan distribusi survival berbeda | Tersedia                            |
| `Cabin` (opsional) | Lokasi kabin → bisa memengaruhi akses ke lifeboat                          | Tersedia tapi banyak missing values |

## 2. Pengambilan Data Menggunakan Python

Pengambilan data menggunakan kagglehub, sehingga bisa langsung digunakan di skrip berikut:

In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.1.4)

In [2]:
import kagglehub
import pandas as pd
import os # Import os module for path manipulation

# Download dataset Titanic
# kagglehub.dataset_download returns the path to the extracted dataset files
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path dataset:", path)

# List contents of the downloaded directory to verify its structure
print("Contents of downloaded directory:", os.listdir(path))

# Load the single Titanic dataset file
# Based on the contents, it's 'Titanic-Dataset.csv' not separate train/test files.
titanic_data = pd.read_csv(os.path.join(path, "Titanic-Dataset.csv"))

# Preview data
titanic_data.head()

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path dataset: /kaggle/input/titanic-dataset
Contents of downloaded directory: ['Titanic-Dataset.csv']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 3. Integrasi Data ke Database atau Repository

 Integrasi data Titanic dilakukan ke dalam database SQLite (titanic_data.db). Ini melibatkan pembuatan koneksi database, pengunggahan pandas DataFrame ke tabel bernama titanic_data, dan verifikasi integrasi dengan melakukan kueri beberapa baris pertama dari database.

In [3]:
import sqlite3

# Buat koneksi database
conn = sqlite3.connect('titanic_data.db')

# Upload data train dan test
titanic_data.to_sql('titanic_data', conn, if_exists='replace', index=False)

# Verifikasi
pd.read_sql('SELECT * FROM titanic_data LIMIT 5', conn)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S